# 1. Its Faster than List and other collections 
# 2. Many mathematical operations available 

In [2]:
import numpy as np
from time import process_time

In [9]:
pythonlist = [i for i in range(0,1000000)]
start_time  = process_time()
pythonlist2 = [i+5*5 for i in pythonlist]
end_time = process_time()
print('Time Taken => ',end_time-start_time)

Time Taken =>  0.015625


In [11]:
nparray = np.array([i for i in range(0,1000000)])
stime = process_time()
nparray = nparray+5*5
etime = process_time()
print('time taken with np --> ',etime-stime)

time taken with np -->  0.0


In [13]:
nparr = np.array([1,2,3,4,7,5,6,67])
print(nparr)
print(type(nparr))

[ 1  2  3  4  7  5  6 67]
<class 'numpy.ndarray'>


In [14]:
nparr.shape

(8,)

In [15]:
nparr2 = np.array([(1,2,3,4),(5,6,7,8)])
nparr2.shape

(2, 4)

In [18]:
nparr3 = np.array([(1,2,3),(4,5,6)],dtype=float)
print(nparr3)
nparr3.shape

[[1. 2. 3.]
 [4. 5. 6.]]


(2, 3)

In [19]:
nparr4 = np.zeros((2,3))
print(nparr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
nparr5 = np.ones((3,4))
print(nparr5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
np.full((3,4),66)

array([[66, 66, 66, 66],
       [66, 66, 66, 66],
       [66, 66, 66, 66]])

In [26]:
#Identity Matrix --> Raows and Column size should be same
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#Random values 

In [30]:
np.random.random((4,4))

array([[0.5665613 , 0.53390895, 0.94551268, 0.63926942],
       [0.18536572, 0.41593688, 0.80936387, 0.63429444],
       [0.84263861, 0.34645535, 0.72079647, 0.03143295],
       [0.26970661, 0.49398643, 0.2352424 , 0.13445525]])

In [32]:
np.random.randint(5,10,(5,5))

array([[7, 9, 8, 6, 9],
       [9, 5, 8, 6, 5],
       [5, 6, 9, 7, 6],
       [9, 8, 9, 6, 7],
       [7, 9, 6, 8, 5]])

In [34]:
np.linspace(5,20,4)

array([ 5., 10., 15., 20.])

In [35]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [36]:
l = [1,2,3,4,54,56,6]
x = np.asarray(l)
print(x)
print(type(x))

[ 1  2  3  4 54 56  6]
<class 'numpy.ndarray'>


In [39]:
c = np.random.randint(5,50,(5,5))
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)

(5, 5)
2
25
int32


In [41]:
l1 = [1,2,3,4]
l2 = [3,4,5]
print(l1+l2) #it will concatinate, not just ADD

[1, 2, 3, 4, 3, 4, 5]


In [43]:
np_l1 = np.array([1,2,3,4])
np_l2 = np.array([3,4,5,6])
print(np_l1+np_l2)

[ 4  6  8 10]


In [46]:
np.subtract(np1,np2)

array([[  2, -51,  -1],
       [ -2,   0,  16],
       [ -4, -17, -13]])

In [47]:
np.multiply(np1,np2)

array([[ 255,  406,  930],
       [1443, 1225,  465],
       [ 621, 2378, 1850]])

In [51]:
x = np.random.randint(2,12,(4,5))
x

array([[ 6, 11, 11,  7,  7],
       [11, 11,  6,  9, 11],
       [ 9,  2,  4, 10,  4],
       [ 2,  8,  3,  7,  5]])

In [52]:
np.transpose(x)

array([[ 6, 11,  9,  2],
       [11, 11,  2,  8],
       [11,  6,  4,  3],
       [ 7,  9, 10,  7],
       [ 7, 11,  4,  5]])

In [53]:
x.T

array([[ 6, 11,  9,  2],
       [11, 11,  2,  8],
       [11,  6,  4,  3],
       [ 7,  9, 10,  7],
       [ 7, 11,  4,  5]])

In [54]:
y = np.random.randint(0,10,(2,3))
y

array([[1, 3, 0],
       [1, 6, 6]])

In [57]:
y.reshape((3,2))

array([[1, 3],
       [0, 1],
       [6, 6]])